ahkscript/awesome-AutoHotkey

- main.css
Modified css to give item boxes better contrast.
> CSS changes

- README.md
See https://github.com/sindresorhus/awesome/issues/253
> Add Awesome badge

- CONTRIBUTING.md
- Historical.md
- README.md
> #47 - Added <Historical.md>

- Historical.md
Creating a pull request for the first entries for the Historical page
> Adding a few old defunct tools

- README.md
> Added AutoGUI - Closed #62

- Historical.md
Fixed #55 by adding vic to historical
> #55 - Added vic

- README.md
Added my own tool, WindowSaver to the window management section.
> WindowSaver

- CONTRIBUTING.md
- Historical.md
- README.md
Passed the builds https://travis-ci.org/ahkscript/awesome-AutoHotkey/branches
> Patch issue #70

- README.md
> #81 - Added Toolbar

- Historical.md
> #95 - Updated Sparrow download link

- README.md
There seem to have been problems rendering in certain cases when a <br> was used :-(
> #132 - Fixing rendering issue

- README.md
Is `Libraries > System` the right section for this library?
> Added Vista Audio Control Functions library

- README.md
> Add KeyPress OSD

- README.md
See discussion https://github.com/ahkscript/awesome-AutoHotkey/issues/145
> Adding 5 DSV libraries, removing "Lists" see #145

- README.md
Adds my project [ahk](https://github.com/spyoungtech/ahk) to the list. Per #167
> Add item: ahk - A Python wrapper for AutoHotkey

- README.md
Adding leya to the database section.
https://github.com/kevgk/Leya
> adding leya, mysql/php database api

- README.md
Add Item: "Open-Show-Apps" (Open, restore or minimize Window's and Chrome's Apps)" in "Scripts - Window Management" section
> Add Item: "Open-Show-Apps"

- README.md
Hello! I'm the creator of [AutoHotkey.py](https://github.com/Perlence/AutoHotkey.py). Could you add it to the list, please?
> Add AutoHotkey.py

- README.md
Hello, 
Im the creator of DateHotkey. A small tool to easily receive date strings of current, previous or upcomming dates.
I just wanted to add DateHotkey to your list.
Kind regards
> Add DateHotkey

- README.md
Add Static Hands project. Link at https://github.com/almogtavor/static-hands
> Add Static Hands
